
#Server settings
server:
  port: 8888
  use-forward-headers: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/plain,text/css,text/xml,text/javascript,application/json,application/javascript,application/xml,application/xml+rss,application/x-javascript,application/x-httpd-php,image/jpeg,image/gif,image/png
  tomcat:
    remote-ip-header: X-Forwarded-for
    protocol-header: X-Forwarded-Proto
    port-header: X-Forwarede-Port
    uri-encoding: UTF-8

#SPRING PROFILES
spring:
  profiles:
    active: '@profileActive@'
  application:
    name: zenos-admin
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true

  #HTTP ENCODING
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  http:
    encoding:
      enabled: true
      charset: UTF-8
  messages:
    encoding: UTF-8
  jmx:
    enabled: true
    default-domain: agentservice
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  banner:
    charset: UTF-8
#Mybatis
mybatis:
  type-aliases-package: com.zhoushan.blog.persistence.beans
  mapper-locations: classpath:/mapper/*.xml

#Mapper
mapper:
  mappers:
    - com.zhoushan.blog.framework.object.BaseMapper
  not-empty: false
  identify: MYSQL

#Pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methos-arguments: true
  params: count=countSql